import 'package:flutter/material.dart';
import 'meal_planner.dart' as planner;
import 'grocery_list.dart' as grocery;
import 'recipe_area.dart';
import 'settings_screen.dart';

class HomeScreen extends StatelessWidget {
  final int userId;

  HomeScreen({required this.userId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => RecipeArea()),
                );
              },
              child: Text('Recipe Area'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => planner.MealPlanner()),
                );
              },
              child: Text('Meal Planner'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => grocery.GroceryList(autoGeneratedItems: [])),
                );
              },
              child: Text('Grocery List'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => SettingsScreen(userId: userId)),
                );
              },
              child: Text('Settings'),
            ),
          ],
        ),
      ),
    );
  }
}